FROM node:5.11
MAINTAINER Facundo Soria Guerrero <fblind@gmail.com>

#Bower Installation
RUN npm install -g bower
RUN npm install -g webpack
RUN npm install -g webpack-dev-server
RUN npm install -g kick

WORKDIR /frontend/app