backend: 
  build: .  
  ports:    
      - "8000:8000"
  environment: 
      ENV: DEV
  volumes: 
      - ./backend:/backend
  command: python manage.py runserver 0.0.0.0:8000
  expose:
      - "8000"

frontend: 
  build: frontend
  ports:
      - "9000:9000"
  net: host
  volumes: 
      - ./frontend/app:/frontend/app
  command: npm start
  expose:
      - "9000"